-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:244170d942e8398d9d333bc806ec13ba$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 0, y = 0, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 365, y = 0, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "10.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 730, y = 0, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "11.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 1095, y = 0, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "12.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 1460, y = 0, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "13.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 0, y = 447, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "14.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 365, y = 447, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "15.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 730, y = 447, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "16.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 1095, y = 447, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "17.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 1460, y = 447, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "18.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 0, y = 894, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "19.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 365, y = 894, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 730, y = 894, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "20.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 0, y = 0, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 1095, y = 894, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 1460, y = 894, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 0, y = 1341, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 365, y = 1341, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 730, y = 1341, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 1095, y = 1341, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "9.png",
				spriteColorRect = { x = 0, y = 0, width = 365, height = 447 },
				textureRect = { x = 1460, y = 1341, width = 365, height = 447 },
				spriteSourceSize = { width = 365, height = 447 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

